// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    voting_sys
    (
        init => init
        addCandidate => add_candidate
        startSession => start_session
        closeSession => close_session
        getResults => get_results
        castVote => cast_vote
        getCandidates => get_candidates
        register => register
        isActive => is_active
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
